name: homebankhack
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  animations: ^2.0.0
  bloc: ^7.2.0
  camera: ^0.9.4+1
  carousel_slider: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_gen: ^4.0.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: 9.1.0
  freezed_annotation: ^0.15.0
  intl: ^0.17.0
  rive: ^0.7.18

dev_dependencies:
  bloc_test: ^8.2.0
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/loading_logo.riv
  fonts:
    - family: Girloy
      fonts:
        - asset: assets/fonts/Gilroy-Black.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Semibold.ttf
        - asset: assets/fonts/Gilroy-Thin.ttf
        - asset: assets/fonts/Gilroy-ThinItalic.ttf
        - asset: assets/fonts/Gilroy-UltraLight.ttf