name: homebankhack
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.0
  camera: ^0.9.4+1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_gen: ^4.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.15.0
  google_ml_kit: ^0.7.2
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  rive: ^0.7.18
  rxdart: ^0.27.2

dev_dependencies:
  bloc_test: ^8.2.0
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/loading_logo.riv